### ISSUE TITLE
implement some layout for playground

### ISSUE THREAD

**Issue by hemedani** [MiaadTeam/lesan#6]
implement some layout for playground

**Comment by hemedani** [comment]
we have some improvements to it

but I will still keep this issue open until the layout is completed.

**Comment by hemedani** [comment]
implement: 

- [] Headers
- [] History
- [] Graph
- [] e2e test

Modal box
<img width="1671" alt="Screen Shot 1402-02-25 at 08 48 58" src="https://github.com/MiaadTeam/lesan/assets/6236123/3f7f920d-4601-48ac-93c6-1973d41eeff8">

**Comment by MahdiTa97** [comment]
I think we have to create other issues for e2e-test and graph features. @hemedani

**Comment by hemedani** [comment]
Maybe, but I think these are not big issues and we can solve them very soon.

**Comment by hemedani** [comment]
I forget to add the document button in the screenshot. please note that. @MahdiTa97

**Comment by hemedani** [comment]
Done
